[project]
name = "thesis-workspace"
version = "0.1.0"
description = "Thesis Workspace for Generative Quantum Machine Learning Models"
requires-python = ">=3.12"
dependencies = [
    "python-lsp-server>=1.14.0",
]

[tool.uv.workspace]
members = [
    "simulations/1-classical-ddpm",
    "simulations/2-qddpm-py",
    "simulations/5-qml-py",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]
thesis-workspace = { workspace = true }

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN", "D", "ERA", "FBT", "INP", "EM", "T20", "PLC0415", "S602", "PLR2004", "PLR1711", "PLR0913", "E501", "N803", "N806", "TRY003", "COM812"]
